In [32]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()

True

In [ ]:

url = ('https://newsapi.org/v2/everything?'
        'q=bitcoin&'
        'from=2026-06-10&to=2026-06-11&'
        'sortBy=popularity&'
        f'apiKey={os.getenv('NEWS_API_KEY')}')

response = requests.get(url)
data = response.json()
data

{'status': 'ok',
 'totalResults': 250,
 'articles': [{'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Rhett Jones',
   'title': 'Crypto Promoters Say Blockchain Is the Future of AI. Researchers Aren’t Buying It',
   'description': 'Is crypto really the secret sauce that AI is missing?',
   'url': 'https://gizmodo.com/crypto-promoters-say-blockchain-is-the-future-of-ai-researchers-arent-buying-it-2000769680',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/03/robot-hodling-bitcoin-1200x675.jpg',
   'publishedAt': '2026-06-10T12:10:43Z',
   'content': 'The crypto industry has been filled with many promoters touting dubious use cases of blockchain technology over the years. At various times in its history, crypto was supposed to revolutionize everyt… [+6186 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Mike Pearl',
   'title': 'Trump Family Reportedly Made About $2.3 Billion on Crypto While Investors Lost About $2.3 Billion on Trump-Related Crypto',
   'description': "It's nice and symmetrical, and also sad.",
   'url': 'https://gizmodo.com/trump-family-reportedly-made-about-2-3-billion-on-crypto-while-investors-lost-about-2-3-billion-on-trump-related-crypto-2000769825',
   'urlToImage': 'https://gizmodo.com/app/uploads/2025/10/gizmodo-social-1200x675-1.jpg',
   'publishedAt': '2026-06-10T02:28:38Z',
   'content': 'Cryptocurrency news can be hard to follow. For instance, I recently encountered the term tokenized coin and spiraled until I could calm myself down with a beveragized drink.\r\nBut a new Reuters report… [+2513 chars]'},
  {'source': {'id': None, 'name': 'Presse-citron'},
   'author': 'Camille Coirault',
   'title': 'Comment la famille Trump s’est enrichie, dopée par une crypto controversée\xa0: une machine à cash à sens unique',
   'description': "Un peu moins d'un an et demi au pouvoir pendant lesquels lui et sa famille se sont gavé de 2,3 milliards de gains en crypto. Le deuxième mandat de Trump est, sans conteste, le plus rentable de l'histoire présidentielle américaine.",
   'url': 'https://www.presse-citron.net/comment-famille-trump-enrichie-crypto-controversee-machine-cash-sens-unique/',
   'urlToImage': 'https://www.presse-citron.net/app/uploads/2025/07/Trump-monnaie-1600x900.jpg',
   'publishedAt': '2026-06-10T11:02:32Z',
   'content': 'Qu’elle nous paraît lointaine l’hostilité affichée de Donald Trump pour les cryptomonnaies : une posture qu’il a tenue durant sa première présidence et jusqu’en 2021. Les temps ont bien changé : aprè… [+5350 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'CoinDesk Indices',
   'title': 'CoinDesk 20 performance update: Index drops 1.4% as all constituents decline',
   'description': 'Bitcoin Cash (BCH) fell 4.1% and NEAR Protocol (NEAR) shed 4.3%, leading the index lower.',
   'url': 'https://www.coindesk.com/coindesk-indices/2026/06/10/coindesk-20-performance-update-index-drops-1-4-as-all-constituents-decline',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/a5d6564e59e7292f80523c554fb4cdb50189e1e2-640x480.png?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T13:23:13Z',
   'content': 'CoinDesk Indices presents its daily market update, highlighting the performance of leaders and laggards in the CoinDesk 20 Index.\r\nThe CoinDesk 20 is currently trading at 1663.81, down 1.4% (-24.03) … [+247 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Omkar Godbole',
   'title': 'The inflation scenario that could send bitcoin tumbling below $60,000',
   'description': 'Your day-ahead look for June 10, 2026',
   'url': 'https://www.coindesk.com/daybook-us/2026/06/10/the-inflation-scenario-that-could-send-bitcoin-tumbling-below-usd60-000',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/d687b13ec3ef7b92cad7c07ff5ad6c8a603ecb40-3999x2666.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T11:20:23Z',
   'content': 'Bitcoin BTC\r\n$61,412.97 is wobbling near $61,000 and data due later today could push it over the edge along with the wider crypto market. \r\nThe U.S. consumer price index for May is due to hit the wir… [+2612 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Jamie Crawley',
   'title': "A 'Bitcoin DeFi' project just shut down with a brutal post-mortem: Users just didn't care",
   'description': 'The project cited market conditions and a broader indifference among the cryptocurrency industry to establishing greater utility on the Bitcoin network.',
   'url': 'https://www.coindesk.com/tech/2026/06/10/a-bitcoin-defi-project-just-shut-down-with-a-brutal-post-mortem-users-just-didn-t-care',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/030d61604f4bdf32cd4013015de2ad6a80a15e24-7200x4800.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T12:00:29Z',
   'content': 'Bitcoin layer-2 network Botanix is being wound down a year after its mainnet went live. \r\nThe project cited market conditions and broader indifference within the cryptocurrency industry towards estab… [+3441 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Shaurya Malwa, Omkar Godbole',
   'title': "Live updates: What next for bitcoin as it faces headwinds from Fed rates to Claude's Mythos",
   'description': "Anthropic's IPO pipeline, not its new model, is what crypto traders should track.",
   'url': 'https://www.coindesk.com/markets/2026/06/10/live-updates-what-next-for-bitcoin-as-it-faces-headwinds-from-fed-rates-to-claude-s-mythos',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/acf831401ea851c7551eb13183b3f53d9be886a8-7146x4766.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T05:47:56Z',
   'content': 'David Nicholas, CEO and Founder of XFUNDs by Nicholas Wealth and portfolio manager of several actively managed ETFs including BLOX, which maintains bitcoin as a core holding, views the current bitcoi… [+822 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Omkar Godbole',
   'title': 'Bitcoin ETFs are no bigger today than when Trump won the election',
   'description': 'Net assets of U.S.-listed spot ETFs have fallen to levels last seen just after Trump won the election in early November 2024.',
   'url': 'https://www.coindesk.com/markets/2026/06/10/bitcoin-etfs-are-no-bigger-today-than-when-trump-won-the-election',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/113d58c52252687aeefe422ee7f400387865a80d-6048x3402.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T05:13:53Z',
   'content': "Bitcoin BTC\r\n$62,194.32 spot exchange-traded funds (ETFs) have fallen out of investor favor and how.\r\nTotal dollar value of net assets across the 11 spot ETFs stood at $77.58 billion on June 9. That'… [+2193 chars]"},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Shaurya Malwa',
   'title': 'Bitcoin and gold fall together as a rate-hike bet hits every hedge',
   'description': "The relief rally that lifted crypto off last week's lows is unwinding alongside tech stocks and gold, with traders bracing for a US inflation print and a Warsh Fed that may stay hawkish.",
   'url': 'https://www.coindesk.com/markets/2026/06/10/bitcoin-and-gold-fall-together-as-a-rate-hike-bet-hits-every-hedge',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/3fefd4274e66ebe6fa9b269e9039d7f0e3e7896d-5000x3111.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T05:22:06Z',
   'content': "Bitcoin's BTC\r\n$61,429.33 bounce from last week's low is rolling over, and gold is going down with it.\r\nBTC changed hands at $61,233 on Wednesday, down 3% over 24 hours and 6.9% on the week, while go… [+2110 chars]"},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Omkar Godbole, Shaurya Malwa',
   'title': 'Zcash, Hyperliquid tokens lead losses as traders bet against a bitcoin bounce',
   'description': 'Crypto markets are under pressure ahead of key U.S. inflation data due later Wednesday.',
   'url': 'https://www.coindesk.com/markets/2026/06/10/zcash-hyperliquid-tokens-lead-losses-as-traders-bet-against-a-bitcoin-bounce',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/3005a1ff5cf6f1c90e49c9a0275a89e7468b0183-1920x1203.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T10:52:54Z',
   'content': 'The crypto market remains under pressure ahead of the pivotal U.S. inflation data, which is expected to show the cost of living rose to a three-year high of over 4% in May.\r\nTokens such as privacy-fo… [+4454 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'James Van Straten',
   'title': "U.S. inflation meets expectations, reinforcing Fed's higher-for-longer stance",
   'description': 'Headline inflation rose an expected 0.5% in May, but the beat on the core rate — which cuts out food and energy costs — is pleasing markets.',
   'url': 'https://www.coindesk.com/markets/2026/06/10/u-s-inflation-meets-expectations-reinforcing-fed-s-higher-for-longer-stance',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/196a178af5d22874394e6f1fc7fcf26b9878e0ea-1440x1080.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T12:42:24Z',
   'content': 'U.S. inflation data came in as expected on Wednesday, reinforcing the view that the Federal Reserve will keep interest rates at 350-375 bps at its June 17 meeting but is likely to increase rates by 2… [+1096 chars]'},
  {'source': {'id': None, 'name': 'CoinDesk'},
   'author': 'Shaurya Malwa',
   'title': "SpaceX's pre-IPO market on Hyperliquid has fallen 27% in three weeks",
   'description': 'The SPCX perpetual still trades above SpaceX’s $135 offer price, but it has fallen sharply from its May highs as traders mark down the first-day premium.',
   'url': 'https://www.coindesk.com/markets/2026/06/10/spacex-s-most-active-pre-ipo-market-has-fallen-27-in-three-weeks',
   'urlToImage': 'https://cdn.sanity.io/images/s3y3vcno/production/97bf2e29eb3c1b7bbc38861e392cdd3baacfcacf-1919x1080.jpg?auto=format&w=960&h=540&crop=focalpoint&fit=clip&q=75&fm=jpg',
   'publishedAt': '2026-06-10T07:18:44Z',
   'content': 'A widely-tracked 5x-leverage perpetual on Hyperliquid tied to SpaceXs impending IPO, expected to be the largest in history, has declined for three consecutive weeks.\r\nThe product, tickered as SPCX, t… [+1742 chars]'},
  {'source': {'id': None, 'name': 'Thedailyupside.com'},
   'author': 'Lilly Riddle',
   'title': 'Hyperliquid ETFs Are Here. Should Advisors Buy the HYPE?',
   'description': 'As bitcoin and Ether falter, Hyperliquid looks poised to outperform.',
   'url': 'https://www.thedailyupside.com/etf/investing-strategies-etf/hyperliquid-etfs-are-here-should-advisors-buy-the-hype/',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/rd6AuIVpnM1Z57.N3nkkgw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD03Njc-/https://media.zenfs.com/en/the_daily_upside_435/5a75c4e9078c1ddc9fd790e034003889',
   'publishedAt': '2026-06-10T04:03:00Z',
   'content': 'Concerned about an AI bubble? Sign up for The Daily Upside for smart and actionable market news, built for investors.\r\nThe cryptocurrency market has officially moved into hyperdrive.\r\nA new ETF from … [+3106 chars]'},
  {'source': {'id': None, 'name': 'Cryptoprowl.com'},
   'author': 'CryptoProwl',
   'title': 'More Than 50% Of Bitcoin Supply Is Now Underwater',
   'description': 'More than half (50%) of Bitcoin’s (CRYPTO: $BTC) circulating supply is now underwater, which means it’s...',
   'url': 'https://www.cryptoprowl.com/releases/more-than-50-of-bitcoin-supply-is-now-underwater-5828',
   'urlToImage': 'https://s.yimg.com/os/en/cryptoprowl_304/0ffd80591401a9444f795ffd8ef1086a',
   'publishedAt': '2026-06-10T13:02:00Z',
   'content': 'More than half (50%) of Bitcoins (CRYPTO: $BTC) circulating supply is now underwater, which means its trading below the price it was purchased at.\xa0\r\nNews that the majority of BTC is underwater comes … [+1222 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Bitcoin and ethereum prices today, June 10, 2026: BTC, ETH open lower and falling further',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_8f31b1b8-a7c2-43c0-a451-39b01dedd80b',
   'urlToImage': None,
   'publishedAt': '2026-06-10T11:47:13Z',
   'content': "If you click 'Accept all', we and our partners, including 248 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'TheStreet'},
   'author': 'Pooja Rajkumari',
   'title': 'Analyst sends blunt message as gold, silver reach multiyear highs',
   'description': 'Gold and silver have had a strong run in 2026, climbing alongside copper and the broader metals complex. As of press time, the per-ounce gold price had climb...',
   'url': 'https://www.thestreet.com/crypto/markets/analyst-sends-blunt-message-as-gold-silver-reach-multiyear-highs',
   'urlToImage': 'https://s.yimg.com/lo/mysterio/api/1D553A537D504FB0740A53CC548524C952FB05B86E3F5E78ED1B5F1E1ADB7974/subgraphmysterio/resizefill_w1200_h801;quality_80;format_webp/https:%2F%2Fmedia.zenfs.com%2Fen%2Fthestreet_881%2F6c3c978fac15301b22d4b904f2c245a4',
   'publishedAt': '2026-06-10T13:30:00Z',
   'content': 'Gold and silver have had a strong run in 2026, climbing alongside copper and the broader metals complex.\xa0\r\nAs of press time, the per-ounce gold price had climbed 3.4% in the past six months while sil… [+2417 chars]'},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': None,
   'title': 'Wall Street Is Moving On From Valuing Core Scientific (CORZ) As A Bitcoin Miner Only, Here’s Why You Should Too',
   'description': None,
   'url': 'https://consent.yahoo.com/v2/collectConsent?sessionId=1_cc-session_f3f9dc7b-dd9f-4f2d-b6ba-7c532475f097',
   'urlToImage': None,
   'publishedAt': '2026-06-10T09:24:10Z',
   'content': "If you click 'Accept all', we and our partners, including 248 who are part of the IAB Transparency &amp; Consent Framework, will also store and / or access information on a device (in other words, us… [+1046 chars]"},
  {'source': {'id': None, 'name': 'Yahoo Entertainment'},
   'author': 'Jabran Kundi',
   'title': 'Despite Downward Target Price Revision, Cipher Digital (CIFR) Remains A Top Mid-Cap AI Stock To Buy',
   'description': 'Cipher Digital Inc. (NASDAQ:CIFR) is one of the 12 Best Mid-Cap AI Stocks to Buy According to Analysts. While Cipher Digital Inc. (NASDAQ:CIFR) received a...',
   'url': 'https://finance.yahoo.com/markets/stocks/articles/despite-downward-target-price-revision-092405647.html',
   'urlToImage': 'https://s.yimg.com/ny/api/res/1.2/bu8x1LhLPOrFCA9Sk8w4hA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyMDA7aD02NzM-/https://media.zenfs.com/en/insidermonkey.com/5502c15f4115fd2e847bac5d3840051b',
   'publishedAt': '2026-06-10T09:24:05Z',
   'content': 'Cipher Digital Inc. (NASDAQ:CIFR) is one of the 12 Best Mid-Cap AI Stocks to Buy According to Analysts. While Cipher Digital Inc. (NASDAQ:CIFR) received a downward price target revision from Morgan S… [+1879 chars]'},
  {'source': {'id': None, 'name': 'Citationneeded.news'},
   'author': 'Andy Baio',
   'title': 'Molly White launches Tech Influence Watch to track AI spending in politics',
   'description': 'Most voters don’t know that crypto and AI companies have spent more than $400\xa0million this cycle to buy Congress. Let’s make that spending visible.',
   'url': 'https://www.citationneeded.news/tech-influence-watch/',
   'urlToImage': 'https://www.citationneeded.news/content/images/2026/06/twitter-image.png',
   'publishedAt': '2026-06-10T00:34:35Z',
   'content': 'Listen to me read this post here (not an AI-generated voice!), subscribe to the feed in your podcast app, or download the recording for later.\r\nIve been running my website Follow the Crypto since 202… [+20669 chars]'},
  {'source': {'id': None, 'name': 'Huffingtonpost.es'},
   'author': 'Tom Bergin, Michelle Conlin, Koh Gui Qing y Tom Wilson',
   'title': 'Según el manual de criptomonedas de Trump, la familia siempre gana (mucho)... pero los inversores no',
   'description': '<![CDATA[<p>Era enero de 2025, la fiebre de las criptomonedas estaba en pleno auge y Donald J. Trump se preparaba para regresar a la Casa Blanca. Así que cuando una amiga de Fatime Elrgdawy le habló de un mensaje en línea del presidente electo de Estados Unid…',
   'url': 'https://www.huffingtonpost.es/economia/segun-manual-criptomonedas-trump-familia-siempre-gana-mucho-inversores-f202606.html',
   'urlToImage': 'https://img2.huffingtonpost.es/files/og_thumbnail/uploads/2026/06/10/imagen-ilustrativa-de-la-criptomoneda-meme-de-donald-trump-y-las-bitcoin.jpeg',
   'publishedAt': '2026-06-10T06:13:29Z',
   'content': 'Era enero de 2025, la fiebre de las criptomonedas estaba en pleno auge y Donald J. Trump se preparaba para regresar a la Casa Blanca. Así que cuando una amiga de Fatime Elrgdawy le habló de un mensaj… [+34134 chars]'},
  {'source': {'id': None, 'name': 'Www.dn.se'},
   'author': 'Hasse Eriksson',
   'title': '13-åringarna som blev börsvinnare – utveckling för olika generationer',
   'description': 'Vad hade hänt om man satsat 10\xa0000 kronor på börsen som 13-åring och sedan låtit pengarna vara i 17 år? Det varierar stort beroende på vilken generation man tillhör – men det finns en tydlig vinnare, visar en genomgång.',
   'url': 'https://www.dn.se/ekonomi/13-aringarna-som-blev-borsvinnare-utveckling-for-olika-generationer/',
   'urlToImage': 'https://static.bonniernews.se/ba/72c118b5-4d54-4752-8291-e582fb80e92d.jpeg?io=1&auto=webp&quality=80&crop=1200:630,smart&width=1200&height=630',
   'publishedAt': '2026-06-10T13:22:42Z',
   'content': 'Det har varit kraftiga börslyft med heta AI-aktier de senaste åren. Samtidigt pågår debatten om att det är en bubbla som kan spricka.\r\nBörshistorien är full av sådana fall och timingen kan betyda myc… [+4215 chars]'},
  {'source': {'id': None, 'name': 'Cointelegraph'},
   'author': 'Cointelegraph by Christina Comben',
   'title': 'Botanix to shut down after 4 years, cites weak demand for Bitcoin DeFi',
   'description': 'The Spiderchain developer told users to withdraw assets by July 9 after concluding demand for Bitcoin-native DeFi was not sufficient to support the network.',
   'url': 'https://cointelegraph.com/news/botanix-says-it-didnt-work-as-bitcoin-scaling-platform-shuts-down-sets-withdrawal-deadline',
   'urlToImage': 'https://s3-images.ctmedia.io/media/article-covers/layoffs-fired-human-resource-hr-leaving-quit-closing-breaking-news.jpg',
   'publishedAt': '2026-06-10T11:45:36Z',
   'content': 'Botanix, a Bitcoin scaling network that set out to bring real utility to BTC without token incentives, is winding down after four years in operation.\r\nIn a Tuesday post on X, Botanix told users to wi… [+2765 chars]'},
  {'source': {'id': None, 'name': 'Cointelegraph'},
   'author': 'Cointelegraph by Yashu Gola',
   'title': 'Bitcoin price may slide toward $30K as institutions dump 450% of daily BTC supply',
   'description': 'Bitcoin’s institutional support is weakening as ETFs and corporates dump almost 2,000 BTC daily and Strategy’s buying loses momentum.',
   'url': 'https://cointelegraph.com/markets/bitcoin-price-may-slip-under-30k-as-institutions-dump-450-of-daily-btc-supply',
   'urlToImage': 'https://s3-images.ctmedia.io/media/article-covers/hi-market-correction-vs-bear-market-btc.jpg',
   'publishedAt': '2026-06-10T13:11:03Z',

In [ ]:
#url = f"https://newsapi.org/v2/top-headlines?country=sa&apiKey={os.getenv('NEWS_API_KEY')}"
#resp = requests.get(url)
#resp.json()

{'status': 'ok', 'totalResults': 0, 'articles': []}

In [ ]:
data.keys()

dict_keys(['status', 'totalResults', 'articles'])

In [25]:
articles = data['articles']
type(articles)

list

In [26]:
articles_df = pd.DataFrame(articles)
articles_df.head()

,source,author,title,description,url,urlToImage,publishedAt,content
0,"{'id': None, 'name': 'Gizmodo.com'}",Rhett Jones,Crypto Promoters Say Blockchain Is the Future ...,Is crypto really the secret sauce that AI is m...,https://gizmodo.com/crypto-promoters-say-block...,https://gizmodo.com/app/uploads/2026/03/robot-...,2026-06-10T12:10:43Z,The crypto industry has been filled with many ...
1,"{'id': None, 'name': 'Gizmodo.com'}",Mike Pearl,Trump Family Reportedly Made About $2.3 Billio...,"It's nice and symmetrical, and also sad.",https://gizmodo.com/trump-family-reportedly-ma...,https://gizmodo.com/app/uploads/2025/10/gizmod...,2026-06-10T02:28:38Z,Cryptocurrency news can be hard to follow. For...
2,"{'id': None, 'name': 'Presse-citron'}",Camille Coirault,"Comment la famille Trump s’est enrichie, dopée...",Un peu moins d'un an et demi au pouvoir pendan...,https://www.presse-citron.net/comment-famille-...,https://www.presse-citron.net/app/uploads/2025...,2026-06-10T11:02:32Z,Qu’elle nous paraît lointaine l’hostilité affi...
3,"{'id': None, 'name': 'CoinDesk'}",CoinDesk Indices,CoinDesk 20 performance update: Index drops 1....,Bitcoin Cash (BCH) fell 4.1% and NEAR Protocol...,https://www.coindesk.com/coindesk-indices/2026...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-10T13:23:13Z,CoinDesk Indices presents its daily market upd...
4,"{'id': None, 'name': 'CoinDesk'}",Omkar Godbole,The inflation scenario that could send bitcoin...,"Your day-ahead look for June 10, 2026",https://www.coindesk.com/daybook-us/2026/06/10...,https://cdn.sanity.io/images/s3y3vcno/producti...,2026-06-10T11:20:23Z,"Bitcoin BTC\r\n$61,412.97 is wobbling near $61..."

In [27]:
articles_df.drop(columns={'source','urlToImage'}, inplace=True)
articles_df.head()

,author,title,description,url,publishedAt,content
0,Rhett Jones,Crypto Promoters Say Blockchain Is the Future ...,Is crypto really the secret sauce that AI is m...,https://gizmodo.com/crypto-promoters-say-block...,2026-06-10T12:10:43Z,The crypto industry has been filled with many ...
1,Mike Pearl,Trump Family Reportedly Made About $2.3 Billio...,"It's nice and symmetrical, and also sad.",https://gizmodo.com/trump-family-reportedly-ma...,2026-06-10T02:28:38Z,Cryptocurrency news can be hard to follow. For...
2,Camille Coirault,"Comment la famille Trump s’est enrichie, dopée...",Un peu moins d'un an et demi au pouvoir pendan...,https://www.presse-citron.net/comment-famille-...,2026-06-10T11:02:32Z,Qu’elle nous paraît lointaine l’hostilité affi...
3,CoinDesk Indices,CoinDesk 20 performance update: Index drops 1....,Bitcoin Cash (BCH) fell 4.1% and NEAR Protocol...,https://www.coindesk.com/coindesk-indices/2026...,2026-06-10T13:23:13Z,CoinDesk Indices presents its daily market upd...
4,Omkar Godbole,The inflation scenario that could send bitcoin...,"Your day-ahead look for June 10, 2026",https://www.coindesk.com/daybook-us/2026/06/10...,2026-06-10T11:20:23Z,"Bitcoin BTC\r\n$61,412.97 is wobbling near $61..."

In [33]:
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASS = os.getenv('DB_PASS')

engine = create_engine(f'postgresql+psycopg2://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

articles_df.to_sql('articles', con= engine, if_exists='replace', index=False)

99

In [34]:
type(response)

requests.models.Response